(define-foreign-type batch (c-pointer "CT_Batch"))
(bind-coati batch:create batch (unsigned-int)
	    (finally %batch:free))
(bind-coati %batch:free void (batch))
(bind-coati batch:push unsigned-int (batch transformation))
(bind-coati batch:remove void (batch unsigned-int))
(bind-coati batch:change void (batch unsigned-int transformation))
(bind-coati batch:render void (batch texture))
(bind-coati batch:size unsigned-int (batch))
