(define-foreign-type texture (c-pointer "CT_Texture"))
(bind-coati image->texture texture (image)
	    (finally %texture:free))
(bind-coati texture:create texture (unsigned-int unsigned-int)
	    (finally %texture:free))
(bind-coati texture:copy texture (texture)
	    (finally %texture:free))
(bind-coati texture:load texture (c-string)
	    (finally %texture:free))
(bind-coati %texture:free void (texture))
(bind-coati texture:screen? bool (texture))
(bind-coati texture:size (f32vector 2) (texture))
(bind-coati texture:clear void (texture f32vector))
(bind-coati texture:render void (texture transformation))
