(bind-coati window:init bool ())
(bind-coati window:quit void ())
(bind-coati %window:resolution-set! void (u32vector))
(bind-coati window:resolution (u32vector 2) ()
	    (parameter %window:resolution-set!))
(bind-coati %window:fullscreen-set! void (bool))
(bind-coati window:fullscreen bool ()
	    (parameter %window:fullscreen-set!))
(bind-coati window:update void ())
(bind-coati window:clear void (f32vector))
